services:
  - type: web
    name: chatbot-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        value: your-real-openai-api-key-here
    plan: free
